var arceusHP =120;
var arceusNum =493;
var arceusType = "normal"
var arceusBestMove = "judgment"
var arceusLastEvo = false;
var arceusAttack =120;
var arceusDefense =120;
var arceusSpeed =120;
var blazikenHP =80;
var blazikenNum =257;
var blazikenType = "fire and fighting"
var blazikenBestMove = "Flare blitz"
var blazikenLastEvo = true;
var blazikenAttack =120;
var blazikenDefense =70;
var blazikenSpeed =80;
var flygonHP =80;
var flygonNum =330;
var flygonType = "Dragon and Ground"
var flygonBestMove = "dragon tail"
var flygonLastEvo = true;
var flygonAttack =100;
var flygonDefense =80;
var flygonSpeed =100;
arceusHP = arceusHP - 50
blazikenHP = blazikenHP - 50
flygonHP = flygonHP - 50
